---
title: "Crime in Phoenix"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
    source: embed
    smart: false
runtime: shiny
---



```{r include = FALSE}

# preprocessing -----------------------------------------------------------

# This imports the data and does a bit of cleaning
# to get it ready for the dashboard


# ----
# clear workspace
rm( list = ls() )

# ----
# load libraries
library( dplyr )         # used for wrangling the data
library( tidyr )         # used for wrangling the data
library( ggplot2 )       # for plotting
library( here )          # for referencing the local directory
library( sf )            # spatial objects
library( tigris )        # to get geographic boundaries
library( leaflet )       # for producing the leaflet plot
library( flexdashboard ) # for the dashboard


# ----
# define the objects
crimeData       <- readRDS( here( "data/crimeData.rds" ) )

```

[The Title of Your Tab]
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}

# user input widgets -----------------------------------------------------------

# ----
# crime type

checkboxGroupInput( inputId = "checkCrimeType" ,
                    label = h3( "Crime Type" ), 
                    choices = list( 
                      "Drugs" = "Drugs",    
                      "Rape" = "Rape",      
                      "Assault" = "Assault",  
                      "Theft" = "Theft",    
                      "MV Theft" = "MV Theft",
                      "Burglary" = "Burglary",
                      "Homicide" = "Homicide", 
                      "Robbery" = "Robbery",  
                      "Arson" = "Arson" ),
                    selected = c(
                      "Drugs", "Rape", "Assault", "Theft", "MV Theft",
                      "Burglary", "Homicide", "Robbery", "Arson" )
                    )

```

Outputs
-------------------------------------

### [The Title of Your Map]

```{r}

# setup the output -----------------------------------------------------------

renderLeaflet({

  dat <- crimeData[ ( crimeData$crime.type %in% input$checkCrimeType ) ,]
    
  phx <- leaflet() %>% 
    addProviderTiles( "CartoDB.Positron" ) %>%
    setView( lng = -112.0740, 
             lat = 33.4484, 
            zoom = 13 )
  
  addCircles( phx, 
             lng = dat$Longitude, 
             lat = dat$Latitude,
             fillOpacity = 0.5, 
             stroke = FALSE
             )

})

```   














