---
title: "Crime in Phoenix"
---

<br>

*What is going on with crime in Phoenix?*

What do you think? Is crime on the rise? Is crime declining? Having a hard time answering that question (**and** *being confident about your answer*)? Well, you should! I certainly do (and [I am a criminologist](https://jacobtnyoung.github.io/)). But, so are most people. [Gallup polling](https://news.gallup.com/poll/268283/describe-problem-crime-serious.aspx) has consistently shown that individuals' perceptions of crime does not (REPEAT **does not**) track trends in crime.  

Crime trends are **very** difficult to assess, without seeing the data, because of the peculiar nature of crime. 

  * First, crime is very concentrated in specific geographic areas and exposure to crime and victimization is disproportionately concentrated among groups. If you are fortunate enough to not experience victimization, then your assessment of the frequency of events probably comes from hearsay or media accounts. These are both "*biased*" accounts in the sense that they do not reflect representative cases of crime. In other words, we tend to hear about things that happen and don't really hear about when things don't happen.  

  * Second, when individuals do experience victimization, they tend to overestimate the prevalence of crime. This makes intuitive sense, but makes it difficult to assess the actual prevalence of crime.  

  * Third, we measure crime very poorly. There is often a large time gap between when crime happens and when those data are compiled into annual reports of crime. 

<br>

This page focuses on analyses that pertain to understanding crime in Phoenix:  

  * [What is going on with crime in Phoenix? (well, let's look!)](https://jacobtnyoung.github.io/OpenCrimPhx/crime-trends.html)  
  * [(More on) What is going on with crime (**types**) in Phoenix?](https://jacobtnyoung.github.io/OpenCrimPhx/crime-types.html)



<br>

----

***Please*** report any needed corrections to the [Issues](https://github.com/jacobtnyoung/OpenCrimPhx/issues/new) page. Thanks!

<br>