---
title: "Crime in Phoenix"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
    source: embed
    smart: false
runtime: shiny
---



```{r include = FALSE}

# ----
# clear workspace
rm( list = ls() )

# ----
# load libraries
library( dplyr )          # used for wrangling the data
library( tidyr )          # used for wrangling the data
library( ggplot2 )        # for plotting
library( here )           # for referencing the local directory
library( sf )             # spatial objects
library( tigris )         # to get geographic boundaries
library( leaflet )        # for producing the leaflet plot
library( flexdashboard )  # for the dashboard
library( leaflet.extras ) # for the heatmap


# ----
# define the objects
crimeData       <- readRDS( here( "data/crimeData.rds" ) )


```

Crimes in Phoenix
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}

# option to select points or heatmap
radioButtons(
  inputId = "mapType",
  label = h4( "Map Display Type:" ),
  choices = c( "Heatmap", "Points" ),
  selected = "Heatmap",
  inline = TRUE
)


# create the check box for the crime type
checkboxGroupInput( 
  inputId = "checkCrimeType" ,
  label = h4( "Crime Type" ), 
  choices = list( 
    "Drugs" = "Drugs",    
    "Rape" = "Rape",      
    "Assault" = "Assault",  
    "Theft" = "Theft",    
    "MV Theft" = "MV Theft",
    "Burglary" = "Burglary",
    "Homicide" = "Homicide", 
    "Robbery" = "Robbery",  
    "Arson" = "Arson" ),
  selected = c( 
    "Drugs", "Rape", "Assault", "Theft", "MV Theft",
    "Burglary", "Homicide", "Robbery", "Arson" 
    ) 
  )


# create a slider for the year
sliderInput(
  inputId = "yearRange",
  label = h4( "Select Year Range:" ),
  min = min( as.numeric( crimeData$year ) ),
  max = max(  as.numeric( crimeData$year ) ),
  value = c( 
    min( as.numeric( crimeData$year ) ), 
    max( as.numeric( crimeData$year ) )
    ),
  sep = "",
  animate = TRUE
)


# slider input for time of day
sliderInput(
  inputId = "hourRange",
  label = h4( "Select Time of Day Range:" ),
  min = min( crimeData$hour ),
  max = max( crimeData$hour ),
  value = c( 
    min( crimeData$hour ),
    max( crimeData$hour )
    ),
  sep = "",
  animate = TRUE
)

```

Outputs
-------------------------------------

### Crimes in Phoenix

```{r}

output$map <- renderLeaflet({

  dat <- crimeData %>%
    filter(
      crime.type %in% input$checkCrimeType,
      year >= input$yearRange[1],
      year <= input$yearRange[2],
      hour >= input$hourRange[1],
      hour <= input$hourRange[2],
      !is.na( Longitude ), !is.na( Latitude ),
      is.finite( Longitude ), is.finite( Latitude )
    )
  
  # randomly sample points to allow it to render faster
  if (input$mapType == "Points" && nrow(dat) > 10000) {
    dat <- dat[sample(nrow(dat), 10000), ]
  }

  map <- leaflet( dat ) %>%
    addProviderTiles( "CartoDB.Positron" ) %>%
    setView( lng = -112.0740, lat = 33.4484, zoom = 12 )

  if ( input$mapType == "Points" ) {

  pal <- colorFactor( palette = "Set1", domain = dat$crime.type )

  map %>%
    addCircles(
      lng = dat$Longitude,
      lat = dat$Latitude,
      color = pal( dat$crime.type ),
      fillOpacity = 0.7,
      stroke = FALSE,
      radius = 30,
      label = paste0(
        "Type: ", dat$crime.type,
        ", Hour: ", dat$hour
      ),
      labelOptions = labelOptions(
        direction = "auto",
        style = list( "font-size" = "12px" ),
        textsize = "12px",
        sticky = FALSE
      )
    ) %>%
    addLegend( "bottomright", pal = pal, values = dat$crime.type,
              title = "Crime Type" )
}
 else {
    map %>% addHeatmap(lng = dat$Longitude, lat = dat$Latitude,
                       blur = 20, radius = 15)
  }
})

leafletOutput( "map" )

```   

